name: Home Assistant

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  hassfest:
    name: Hassfest
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@main"
      - uses: home-assistant/actions/hassfest@master
